# Generated by Django 3.0 on 2019-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=255)),
                ('Sprint_Name', models.CharField(max_length=100)),
                ('Resource_Name', models.CharField(max_length=255)),
                ('Planned_Deliverables', models.TextField()),
                ('Delivery_date', models.DateTimeField()),
                ('Challenges_Faced', models.TextField()),
            ],
        ),
    ]
